import { spawn } from 'node:child_process';
import puppeteer from 'puppeteer-core';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const server = spawn('python3', ['-m', 'http.server', '8080'], { cwd: ROOT });
await new Promise((r) => server.once('spawn', r));
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const page = await browser.newPage();
await page.goto('http://127.0.0.1:8080/app/', { waitUntil: 'load', timeout: 120000 });
await page.waitForFunction('window.__oo && window.__oo.ready === true', { timeout: 180000 });
const out = await page.evaluate(() => {
  const m = window.__oo.module;
  const R = {};
  const E = (cmd) => { const s = m.eval_string(cmd); return { s, e: m.last_error_message() }; };
  R.tk = E('disp(["figtk=", get(gcf, "__graphics_toolkit__")]);');
  R.avail = E('disp(available_graphics_toolkits());');
  R.loaded = E('disp(loaded_graphics_toolkits());');
  R.dirty = E('figure(2); plot(rand(5,1)); drawnow;');
  R.gp = (() => { try { return 'size=' + m.FS.stat('/plot.gp').size; } catch (e) { return 'absent'; } })();
  R.output = document.getElementById('output').textContent;
  return R;
});
console.log(JSON.stringify(out, null, 2));
await browser.close(); server.kill(); process.exit(0);
